version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/storage
      - /var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.knurdrijfqfrbhdcnpak
      - DB_PASSWORD=1234
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge